//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        public int Id { get; set; }
        public string jobtitle { get; set; }
        public string responsibilities { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string location { get; set; }
        public string contactnumberemail { get; set; }
        public Nullable<int> forid { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
